### ISSUE TITLE
Related reflection problems

### ISSUE THREAD

**Issue by kristianmandrup** [niflostancu/polymer-reflection#1]
Hi Florin,

I've been experimenting with my own "reflection" so far, however I'm hitting a mysterious issue.

I have a callback `Polymer.registered = function(proto) { ...}` which if present is called when the element is registered.

However, inside this callback function, if I access a property of the prototype like this:  `proto[name]` even for logging, like:

``` js
Polymer.registered = function(proto) { 
  console.log('prop', proto[name]);
}
```

Then my bindings fail with `Uncaught TypeError: Cannot read property 'title' of undefined` when trying to access the property later. Just wondering if you ran into this issue and found away around it?
Perhaps I should `clone` the object?

Sorry to write you here, but thought it was the easiest way to reach you.

**Comment by niflostancu** [comment]
Hello,

Can you give me a concrete example?

Have you tried to print e.g. `proto.properties` for a simple custom element?
As far as I know, the Polymer prototype shouldn't have any getters / setters defined on it (they will be created for each instance of the element), so a simple property read should not have those side effects.

I read your code at [0]. I see you copied the main Polymer entry point code and added your own callback there. This is pretty ugly, if the Polymer devs edit even one line of this function, it could make the whole application crash / behave in unexpected ways.

Are you sure that Polymer works as intended with your runtime modifications?
Are you including your library exactly after the polymer imports?

[0] https://github.com/kristianmandrup/polymer-ext/blob/master/polymer-ext.html

**Comment by kristianmandrup** [comment]
Hi Florian, 

Thanks for your feedback.
I solved it by iterating property names via `Object.keys`. Very odd.
My only problem now is to hack into the `_template` property. IF I can somehow set the template to be used for an element before it is stamped... or somehow hack into this flow? Any ideas ;)

I basically set `prototype._template` (innerHTML) just before the call to `document.registerElement(prototype.is, options);`

But my binding `{{ name }}` inserted in the innerHTML as in `<h2>{{ name }}</h2>` magically disappear :o

**Comment by kristianmandrup** [comment]
Yes, I know this is super "hacky"!!! 

I'm trying to hack into the template here.

``` js
  Polymer.Base._addFeature({
    // override!!
    _prepTemplate: function() {
      // locate template using dom-module
      this._template =
        this._template || Polymer.DomModule.import(this.is, 'template');

      if (typeof this.templator == 'function') {
        this.templator(this._template);
      } else {
        console.log('no templator defined', this);
      }

      // bootstrap the template if it has not already been
      if (this._template && !this._template.content && HTMLTemplateElement.bootstrap) {
        HTMLTemplateElement.decorate(this._template);
        // recurse if necessary
        HTMLTemplateElement.bootstrap(this._template.content);
      }
```

Perhaps I should try to leverage your library instead?

**Comment by niflostancu** [comment]
The `_template` property is available on the prototype after the prototype is initialized and `_prepTemplate` is called (see https://github.com/Polymer/polymer/blob/master/polymer.html#L36 and https://github.com/Polymer/polymer/blob/master/src/mini/template.html). 

So I suggest patching this to run your extension code.

My library doesn't handle registration features other than the callback, but you can inspire from it on the method interception matter.

**Comment by kristianmandrup** [comment]
It works now :) Turns out that the binding syntax is supposed to be removed when it is stamped. I just had a "bad connection" on the binding. Cheers!!

**Comment by kristianmandrup** [comment]
BTW: The `iron-form` you got. Is that using reflection with custom validation? Sounds kinda sweet. 
Would be nice to keep in touch. Are you on the polymer slack channel?

**Comment by niflostancu** [comment]
Glad you figured it out.

I used reflection to augument the standard iron-input / iron-paper / etc. elements with behaviors that provide integration with a custom form component.

This custom form provides automatic value binding to a `model` property, e.g. if you have an input with the name "firstName", it will automatically map it to the `model.firstName` property of the form. This is useful because you can take the entire model object, serialize it and send it to the server (and vice versa for loading the data).
Other features include advanced validation (required, min / max / date validation, all easily extensible) and a framework to make inputs dynamically-instantiable from a template object (i.e. the form to be customizable by the user, think of an application builder).

Sadly, the components I'm working on are experimental / closed source for the moment, but maybe we'll decide to open source them in the future ;)
